version: '3.4'
services:
    mysql:
      ports:
        - "3306:3306"
      expose:
      # Opens port 3306 on the container
        - '3306'
      volumes:
        - db-volume:/var/lib/mysql
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: CondoGest 

    php:
      volumes:
        - .docker/etc/apache/server.pem:/etc/ssl/certs/server.pem
        - .docker/etc/apache/server-key.pem:/etc/ssl/private/server-key.pem
        - .docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
        - db-volume:/var/www/html
      ports:
        - 80:80
  #      - 443:443
      restart: always

    phpmyadmin:
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=root
      links:
        - mysql
      restart: always

    user:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
      ports:
        - "49160:80"
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      restart: always

    condominium:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
      ports:
        - "49162:80"
      restart: always
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    account:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
      ports:
        - "49164:80"
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      restart: always

    bff:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
      ports:
        - "49166:80"
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      restart: always

    web:
      stdin_open: true
      volumes:
        - .:/app
      ports:
        - '49168:80'
      environment:
        - NODE_ENV=development
      restart: always

volumes:
  db-volume:
        