version: '3.4'

services:

    mysql:
        ports:
            - "3306:3306"
        volumes:
            - db-volume:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            - mynetwork

    php:
        volumes:
          - .docker/etc/apache/server.pem:/etc/ssl/certs/server.pem
          - .docker/etc/apache/server-key.pem:/etc/ssl/private/server-key.pem
          - .docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
          - db-volume:/var/www/html
        ports:
          - 80:80
    #      - 443:443
        restart: always
        networks:
          - mynetwork

    phpmyadmin:
        ports:
          - 8080:80
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql
          - PMA_USER=root
          - PMA_PASSWORD=root
        links:
          - mysql
        restart: always
        networks:
          - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
    db-volume:
        